### ISSUE TITLE
训练报错

### ISSUE THREAD

**Issue by 2132660698** [see2023/Bert-VITS2-ext#1]
你好，我在训练的时候报错，麻烦看一下。
![image](https://github.com/see2023/Bert-VITS2-ext/assets/94035926/19c5ace9-bc49-42cb-b59c-e43bb7736af9)
不知道是不是数据处理的时候报错的原因：
![image](https://github.com/see2023/Bert-VITS2-ext/assets/94035926/f26b5e4d-0bb5-4ac0-bb32-3548c14f057d)

模型用的这个：https://huggingface.co/WenYee/Bert-VITS2/tree/main

**Comment by see2023** [comment]
我不清楚你这个模型是什么版本的，我用的是官方 2.3版本训练的。
https://huggingface.co/OedoSoldier/Bert-VITS2-2.3
编码后的隐变量应该是[batch_size, hidden_channels, seq_len]，你的数据多了一个维度，可以先换下模型看看吧；或者用squeeze处理，但这样改的话应该涉及不止一个地方

**Comment by 2132660698** [comment]
换了你发的这个模型（https://huggingface.co/OedoSoldier/Bert-VITS2-2.3）也不行，能把你的torch、torchaudio的版本发一下么。

**Comment by see2023** [comment]
现在是
torch                          2.2.1+cu121
torchaudio                     2.2.1+cu121
升级前是2.1.*，tensor size是一样的。

对于20秒左右的音频，
torchaudio.load得到的audio是torch.Size([1, 1, 880640])
spectrogram_torch得到的spec是torch.Size([1, 1025, 1720])
编码后的z是torch.Size([1, 192, 1720])

另外，训练前用ffmpeg统一采用成44100、单通道了

**Comment by 2132660698** [comment]
将声音按照下面的办法改成单声道就好了：
# 音频截取转换
ffmpeg -i input_file -ss 00:00:00 -t 00:00:10 -ar 44100 -f wav test.wav

# 保留通道1
ffmpeg -i test.wav -map_channel 0.0.0 output.wav

但现在跑完3000epochs后出现下面的报错：
![image](https://github.com/see2023/Bert-VITS2-ext/assets/94035926/221e080c-aa89-4454-b40e-f5688615b528)
我的Bert-VITS2-ext-main\configs\config.json配置如下：
![image](https://github.com/see2023/Bert-VITS2-ext/assets/94035926/a9615e3a-b674-4cfd-ad21-dc195b4c5c66)

下面这了个文件是执行数据预处理：python ./motion/prepare_visemes.py这步生成的。
"training_visemes_files": "filelists/train_visemes.list",
"validation_visemes_files": "filelists/val_visemes.list",

请问下面这两个文件是怎么生成的：
"training_files": "filelists/train.list",
"validation_files": "filelists/val.list",

**Comment by see2023** [comment]
python ./motion/prepare_visemes.py
就是你上面说的这个脚本生成的啊，现在的策略非常简单，就前几个当做验证集，后面的是训练集。
通常都是随机挑选一定的比例当做验证集，不过我自己跑的时候数据量也就不到一百条，随手挑了几个放到validation_files里

**Comment by 2132660698** [comment]
执行下面这步骤：
![image](https://github.com/see2023/Bert-VITS2-ext/assets/94035926/4711fc18-3601-4855-b990-b1d4375fad6f)
生成的文件只有两个：
![image](https://github.com/see2023/Bert-VITS2-ext/assets/94035926/d9145e15-0d55-4e28-87e9-3f856cea7bfb)
![image](https://github.com/see2023/Bert-VITS2-ext/assets/94035926/7e7c7cd1-3315-4db3-9a5a-e2ab3f3bd4e8)
![image](https://github.com/see2023/Bert-VITS2-ext/assets/94035926/9e34b820-a723-460f-822d-a19a64cf86ba)

现在报错的是这两个文件找不到，是不是你之前就已经生成过了，而我这没有生成呢？
![image](https://github.com/see2023/Bert-VITS2-ext/assets/94035926/2ba49238-f58f-40dc-b5df-04fce447bef3)

**Comment by 2132660698** [comment]
现在训练后目录下有文件生成：
![image](https://github.com/see2023/Bert-VITS2-ext/assets/94035926/22a7cd26-24c7-42d9-95a2-d9d26858ccdc)

**Comment by see2023** [comment]
你画框的是原本tts部分的模型的训练文件，表情的文件在下面两行。 
下面生成了V_xxx.pth 就是表情部分的模型。
然后你要自己看loss和实际的效果判断多少步比较合适

**Comment by 2132660698** [comment]
好的，已经跑通了，非常感谢你的支持。

**Comment by see2023** [comment]
OK
