### ISSUE TITLE
大佬，请问下声音到表情的数据集是有公开么，还是要自己制作

### ISSUE THREAD

**Issue by CasonTsai** [see2023/Bert-VITS2-ext#3]
大佬，非常感谢你的工作，我想问下，就是在tts算法里面加了一个支路来预测bs，这个是否有对应的数据集和标签？请问网络是有这样的公开的数据集么

**Comment by see2023** [comment]
没有公开数据集，我是自己觉得这二者可能存在关联，然后自己用ios的live link录了一些数据测试的。
就是项目里record.py，每20秒一次录了几十次，但表情控制的也不太好，所以也就没有公开数据集
