### ISSUE TITLE
MotionGPT计算出骨骼相对父节点的旋转变化量源码vmc_cli.py，参数疑问

### ISSUE THREAD

**Issue by d2623587501** [see2023/Bert-VITS2-ext#4]
大佬您好，感谢您的开源贡献。
目前，我通过MotionGPT得到了3d空间坐标信息数据，维度为[196, 22, 3]，其中196为视频帧数，22为关键点数，3为空间坐标xyz，matplotlib可视化效果如下：

https://github.com/user-attachments/assets/40a06d44-c5ec-456c-bc07-736ad8bcf9ca

打算将动作加载到unity3d，需要进行数据旋转转换，看您vmc_cli.py源码中存在'--a2p_rotations_files'和'--positions_files'两个参数，请问MotionGPT得到了3d空间坐标信息数据对应的是那个参数，及另一个参数文件是如何获得的。

**Comment by d2623587501** [comment]
https://github.com/user-attachments/assets/bdff697d-4c01-44de-bac3-4075766ab56c

**Comment by see2023** [comment]
好久没看这个动画了，MotionGPT我记得只能产出骨骼坐标吧？那就用 positions_files ，vmc这个工具本身就是u3d的吧。
我测试的时候是利用vmc协议发给Metahuman，只有坐标没有旋转的话，有些姿势看起来会很奇怪，比如手掌的朝向不对。
后来我从audio2photoreal里导出了他的动画数据， 他是可以输出旋转变换的，但是我测试下来这个旋转体系的输出变换出来总是有bug，应该是我的变换方式不对。
可能还得你仔细研究一下了，我对动画系统也不太熟悉。
感觉ai动画满足一下简单的Avatar还凑合，离实用还差不少距离，当然这是快一年前的情况了，后续进展我没跟进

**Comment by d2623587501** [comment]
好的好的  感谢大佬的解答
